# Olio-ohjelmointi harjoitustyö Nginx backend conf
#
# Pakolliset muutokset
# ${SERVER_FQDN}        esim: testi.mikxus.dev
# ${TLS_CERT_PATH}      esim: /etc/letsencrypt/live/testi.mikxus.dev/fullchain.pem
# ${TLS_KEY_PATH}       esim: /etc/letsencrypt/live/testi.mikxus.dev/privkey.pem
# ${BACKEND_UPSTREAM}   esim: http://127.0.0.1:3333
# ${ACME_WEBROOT}       esim: /var/www/certbot

server {
    listen 80;

    server_name ${SERVER_FQDN};
    
    # Allow acme challenges
    location ^~ /.well-known/acme-challenge/ {
        root ${ACME_WEBROOT};
        default_type text/plain;
        try_files $uri =404;
    }

    location / {
        return 308 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name ${SERVER_FQDN};

    ssl_certificate ${TLS_CERT_PATH};
    ssl_certificate_key ${TLS_KEY_PATH};

    add_header Strict-Transport-Security "max-age=31536000" always;

    # : D
    location / {
        return 418;
    }

    location /api/ {
        proxy_pass ${BACKEND_UPSTREAM}/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Request-Id $request_id;
    }
}