CREATE TABLE IF NOT EXISTS lahjat (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    lahja TEXT NOT NULL,
    hinta NUMERIC NOT NULL,
    valmistaja TEXT NOT NULL
);