# Auth
quarkus.oidc.application-type=service
quarkus.oidc.auth-server-url=https://auth.mikxus.dev/application/o/test/
quarkus.oidc.token.issuer=https://auth.mikxus.dev/application/o/test/
quarkus.oidc.token.audience=${APP_OAUTH_CLIENT_ID}
quarkus.oidc.authorization-path=https://auth.mikxus.dev/application/o/authorize/
quarkus.oidc.token-path=https://auth.mikxus.dev/application/o/token/
quarkus.oidc.user-info-path=https://auth.mikxus.dev/application/o/userinfo/
quarkus.oidc.end-session-path=https://auth.mikxus.dev/application/o/test/end-session/
quarkus.oidc.jwks-path=https://auth.mikxus.dev/application/o/test/jwks/
quarkus.oidc.roles.role-claim-path=groups

# postgress DB
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=jdbc:postgresql://db:${DB_PORT:5432}/${DB_NAME}